BlogWebApp/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Diagnostics;
using BlogWebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BlogWebApp.Services;

namespace BlogWebApp.Controllers
{
    public class BlogController : Controller
    {

        private readonly ILogger<BlogController> _logger;
        private readonly IBlogCosmosDbService _blogDbService;

        public BlogController(ILogger<BlogController> logger, IBlogCosmosDbService blogDbService)
        {
            _logger = logger;
            _blogDbService = blogDbService;
        }


        [Route("")]
        public async Task<IActionResult> HomePage()
        {
            var m = new BlogHomePageViewModel();

            var blogPosts = await _blogDbService.GetBlogPostsMostRecentAsync(5);

            m.BlogPostsMostRecent = blogPosts;

            return View(m);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        [Route("blogerror")]
        public IActionResult BlogError()
        {
            return View(new BlogErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [Route("Privacy")]
        public async Task<IActionResult> Privacy()
        {
            return View();
        }

    }
}

BlogWebApp/Controllers/BlogPostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Diagnostics;
using BlogWebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BlogWebApp.Services;
using Microsoft.AspNetCore.Authorization;
using BlogWebApp.Models;
using System.Security.Claims;

namespace BlogWebApp.Controllers
{
    public class BlogPostController : Controller
    {

        private readonly ILogger<BlogController> _logger;
        private readonly IBlogCosmosDbService _blogDbService;

        public BlogPostController(ILogger<BlogController> logger, IBlogCosmosDbService blogDbService)
        {
            _logger = logger;
            _blogDbService = blogDbService;
        }

        [Route("post/{postId}")]
        public async Task<IActionResult> PostView(string postId)
        {
            var bp = await _blogDbService.GetBlogPostAsync(postId);

            if (bp == null)
            {
                return View("PostNotFound");
            }

            var comments = await _blogDbService.GetBlogPostCommentsAsync(postId);

            var userLikedPost = false;

            if (User.Identity.IsAuthenticated)
            {
                var userId = User.Claims.FirstOrDefault(p => p.Type == ClaimTypes.NameIdentifier).Value;
                var like = await _blogDbService.GetBlogPostLikeForUserIdAsync(postId, userId);
                userLikedPost = like != null;
            }

            var m = new BlogPostViewViewModel
            {
                PostId = bp.PostId,
                Title = bp.Title,
                Content = bp.Content,
                CommentCount = bp.CommentCount,
                Comments = comments,
                UserLikedPost = userLikedPost,
                LikeCount = bp.LikeCount,
                AuthorId = bp.AuthorId,
                AuthorUsername = bp.AuthorUsername
            };
            return View(m);
        }


        [Route("post/new")]
        [Authorize("RequireAdmin")]
        public IActionResult PostNew()
        {

            var m = new BlogPostEditViewModel
            {
                Title = "",
                Content = ""
            };
            return View("PostEdit", m);
        }



        [Route("post/edit/{postId}")]
        [Authorize("RequireAdmin")]
        public async Task<IActionResult> PostEdit(string postId)
        {
            var bp = await _blogDbService.GetBlogPostAsync(postId);

            if (bp == null)
            {
                return View("PostNotFound");
            }

            var m = new BlogPostEditViewModel
            {
                Title = bp.Title,
                Content = bp.Content
            };
            return View(m);
        }


        [Route("post/new")]
        [Authorize("RequireAdmin")]
        [HttpPost]
        public async Task<IActionResult> PostNew(BlogPostEditViewModel blogPostChanges)
        {
            if (!ModelState.IsValid)
            {
                return View("PostEdit", blogPostChanges);
            }


            var blogPost = new BlogPost
            {
                PostId = Guid.NewGuid().ToString(),
                Title = blogPostChanges.Title,
                Content = blogPostChanges.Content,
                AuthorId = User.Claims.FirstOrDefault(p => p.Type == ClaimTypes.NameIdentifier).Value,
                AuthorUsername = User.Identity.Name,
                DateCreated = DateTime.UtcNow,
            };

            //Insert the new blog post into the database.
            await _blogDbService.UpsertBlogPostAsync(blogPost);

            //Show the view with a message that the blog post has been created.
            ViewBag.Success = true;

            return View("PostEdit", blogPostChanges);
        }


        [Route("post/edit/{postId}")]
        [Authorize("RequireAdmin")]
        [HttpPost]
        public async Task<IActionResult> PostEdit(string postId, BlogPostEditViewModel blogPostChanges)
        {
            if (!ModelState.IsValid)
            {
                return View(blogPostChanges);
            }

            var bp = await _blogDbService.GetBlogPostAsync(postId);

            if (bp == null)
            {
                return View("PostNotFound");
            }

            bp.Title = blogPostChanges.Title;
            bp.Content = blogPostChanges.Content;

            //Update the database with these changes.
            await _blogDbService.UpsertBlogPostAsync(bp);

            //Show the view with a message that the blog post has been updated.
            ViewBag.Success = true;

            return View(blogPostChanges);
        }



        [Route("post/{postId}/comment/new")]
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> PostCommentNew(string postId, string comment)
        {

            if (!string.IsNullOrWhiteSpace(comment))
            {
                var bp = await _blogDbService.GetBlogPostAsync(postId);

                if (bp != null)
                {
                    var blogPostComment = new BlogPostComment
                    {
                        CommentId = Guid.NewGuid().ToString(),
                        PostId = postId,
                        CommentContent = comment,

                        CommentAuthorId = User.Claims.FirstOrDefault(p => p.Type == ClaimTypes.NameIdentifier).Value,
                        CommentAuthorUsername = User.Identity.Name,
                        CommentDateCreated = DateTime.UtcNow
                    };

                    await _blogDbService.CreateBlogPostCommentAsync(blogPostComment);
                }
            }

            return RedirectToAction("PostView", new { postId = postId });
        }


        [Route("post/{postId}/like")]
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> PostLike(string postId)
        {

            var bp = await _blogDbService.GetBlogPostAsync(postId);

            if (bp != null)
            {

                //Check that this user has not already liked this post
                var userId = User.Claims.FirstOrDefault(p => p.Type == ClaimTypes.NameIdentifier).Value;
                var like = await _blogDbService.GetBlogPostLikeForUserIdAsync(postId, userId);

                if (like == null)
                {
                    var blogPostLike = new BlogPostLike
                    {
                        LikeId = Guid.NewGuid().ToString(),
                        PostId = postId,

                        LikeAuthorId = User.Claims.FirstOrDefault(p => p.Type == ClaimTypes.NameIdentifier).Value,
                        LikeAuthorUsername = User.Identity.Name,
                        LikeDateCreated = DateTime.UtcNow
                    };

                    await _blogDbService.CreateBlogPostLikeAsync(blogPostLike);
                }
            }

            return RedirectToAction("PostView", new { postId = postId });
        }

        [Route("post/{postId}/unlike")]
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> PostUnlike(string postId)
        {

            var bp = await _blogDbService.GetBlogPostAsync(postId);

            if (bp != null)
            {
                var userId = User.Claims.FirstOrDefault(p => p.Type == ClaimTypes.NameIdentifier).Value;
                await _blogDbService.DeleteBlogPostLikeAsync(postId, userId);
            }

            return RedirectToAction("PostView", new { postId = postId });
        }

    }
}

BlogWebApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Diagnostics;
using BlogWebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BlogWebApp.Services;
using Microsoft.AspNetCore.Authorization;
using BlogWebApp.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;

namespace BlogWebApp.Controllers
{
    public class UserController : Controller
    {

        private readonly ILogger<BlogController> _logger;
        private readonly IBlogCosmosDbService _blogDbService;

        public UserController(ILogger<BlogController> logger, IBlogCosmosDbService blogDbService)
        {
            _logger = logger;
            _blogDbService = blogDbService;
        }


        [Route("user")]
        [Authorize]
        public async Task<IActionResult> UserProfile()
        {
            var username = User.Identity.Name;

            var m = new UserProfileViewModel
            {
                OldUsername = username,
                NewUsername = username
            };
            return View(m);
        }


        [Route("user")]
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> UserProfile(string newUsername)
        {

            var oldUsername = User.Identity.Name;

            if (newUsername != oldUsername)
            {
                //Update username
                var u = await _blogDbService.GetUserAsync(oldUsername);

                //set the new username on the user object.
                u.Username = newUsername;

                await _blogDbService.UpdateUsernameAsync(u, oldUsername);

                //log out user and let them log in as the new username
                await HttpContext.SignOutAsync();

                ViewBag.Success = true;
            }

            var m = new UserProfileViewModel
            {
                OldUsername = newUsername,
                NewUsername = newUsername
            };

            return View(m);
        }


        [Route("user/{userId}/posts")]
        public async Task<IActionResult> UserPosts(string userId)
        {
            var posts = await _blogDbService.GetBlogPostsForUserId(userId);

            var username = "";

            var firstPost = posts.FirstOrDefault();
            if (firstPost != null)
            {
                username = firstPost.AuthorUsername;
            }

            var m = new UserPostsViewModel
            {
                Username = username,
                Posts = posts
            };
            return View(m);
        }


    }
}

BlogWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Azure Cosmos DB Blog Example</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    @RenderSection("Head", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Blog" asp-action="HomePage">Azure Cosmos DB Blog Example</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <p class="navbar-text text-dark"><span class="d-sm-none d-md-inline">Signed in as </span>@User.Identity.Name</p>
                                <p class="navbar-text text-dark d-none d-sm-none d-md-inline">|</p>
                            </li>
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="BlogPost" asp-action="PostNew">New <span class="d-sm-none d-md-inline">Blog </span>Post</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="UserProfile">My Profile</a>
                            </li>
                            <li class="nav-item">
                                <form class="form-inline" asp-controller="Account" asp-action="Logout">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Azure Cosmos DB Blog Example - <a asp-area="" asp-controller="Blog" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
 </body>
</html>